version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sentry/sentry-laravel
    versions:
    - 2.4.0
    - 2.4.1
    - 2.4.2
    - 2.5.0
  - dependency-name: laravel-lang/lang
    versions:
    - 8.0.3
    - 8.1.0
    - 8.1.1
    - 8.1.2
    - 9.0.0
    - 9.0.1
  - dependency-name: filp/whoops
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.2
    - 9.5.3
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - WebsiteDeveloper
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.3
    - 1.1.4
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.1.1
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.3.0
    - 2.3.1
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: sass-loader
    versions:
    - 11.0.0
  - dependency-name: vuetify-loader
    versions:
    - 1.7.1
