name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute vue-cli build
      run: |
        cd frontend
        rm -rf ../public/{js,css,img}
        yarn install
        ./node_modules/.bin/vue-cli-service build --no-clean
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        TELESCOPE_ENABLED: false
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
